/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class Lance */

#ifndef _Included_Lance
#define _Included_Lance
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     Lance
 * Method:    hello
 * Signature: (Ljava/lang/String;)Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_Lance_hello
  (JNIEnv *, jclass, jstring);

#ifdef __cplusplus
}
#endif
#endif
