/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class lance_Lance */

#ifndef _Included_lance_Lance
#define _Included_lance_Lance
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     lance_Lance
 * Method:    hello
 * Signature: (Ljava/lang/String;)Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_lance_Lance_hello
  (JNIEnv *, jclass, jstring);

/*
 * Class:     lance_Lance
 * Method:    newDataset
 * Signature: (Ljava/lang/String;Ljava/util/Optional;Ljava/util/Optional;Ljava/util/Optional;)J
 */
JNIEXPORT jlong JNICALL Java_lance_Lance_newDataset
  (JNIEnv *, jclass, jstring, jobject, jobject, jobject);

/*
 * Class:     lance_Lance
 * Method:    countRows
 * Signature: (J)J
 */
JNIEXPORT jlong JNICALL Java_lance_Lance_countRows
  (JNIEnv *, jclass, jlong);

#ifdef __cplusplus
}
#endif
#endif
